name: Build and Deploy
permissions:
Â  contents: write
on:
Â  push:
Â  Â  branches:
Â  Â  Â  - main
jobs:
Â  build-and-deploy:
Â  Â  runs-on: ubuntu-latest
Â  Â  concurrency: ci-${{ github.ref }}
Â  Â  steps:
Â  Â  Â  - name: Checkout
Â  Â  Â  Â  uses: actions/checkout@v2
Â  Â  Â  - uses: actions/setup-node@v1
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  node-version: '16.13.2'

Â  Â  Â  - name: Install and Build ðŸ”§
Â  Â  Â  Â  run: |Â 
Â  Â  Â  Â  Â  npm ci
Â  Â  Â  Â  Â  npm run build Â  Â  Â  Â 
Â  Â  Â  - name: DeployÂ 
Â  Â  Â  Â  uses: JamesIves/github-pages-deploy-action@v4
Â  Â  Â  Â  with:
Â  Â  Â  Â  Â  branch: release #The branch the action should deploy to.
Â  Â  Â  Â  Â  folder: . # The folder the action should deploy.
          repository: aspcodenet/MyQuizSite.git
